[package]
name = "gpui-pre-http-client-tls"
version = "0.3.99"
edition = { workspace = true }
publish = true
license = "Apache-2.0"
description = "Zed's `http_client_tls` crate (gpui-pre snapshot of zed@aeaf3b4)"
repository = "https://github.com/zed-industries/zed"

[package.metadata.gpui-pre]
zed-crate = "http_client_tls"
zed-version = "0.1.0"
zed-rev = "aeaf3b4f20a23cf002f678ef925e6a9a02f00358"

[lib]
path = "src/http_client_tls.rs"
doctest = true
name = "http_client_tls"

[features]
test-support = []

[dependencies]
log = { workspace = true }
rustls = { workspace = true }
rustls-platform-verifier = { workspace = true }
webpki-roots = { workspace = true }

[lints]
workspace = true
