[package]
name = "gpui-pre-http-client-tls"
version = "0.3.120"
edition = { workspace = true }
publish = true
license = "Apache-2.0"
description = "Zed's `http_client_tls` crate (gpui-pre snapshot of zed@7485783)"
repository = "https://github.com/zed-industries/zed"

[package.metadata.gpui-pre]
zed-crate = "http_client_tls"
zed-version = "0.1.0"
zed-rev = "7485783f8027adba8795bcc2341bff7158791b3d"

[lib]
path = "src/http_client_tls.rs"
doctest = false
test = false
name = "http_client_tls"

[features]
test-support = []

[dependencies]
log = { workspace = true }
rustls = { workspace = true }
rustls-platform-verifier = { workspace = true }
webpki-roots = { workspace = true }

[lints]
workspace = true
