[package]
name = "gpui-pre-http-client-tls"
version = "0.3.125"
edition = { workspace = true }
publish = true
license = "Apache-2.0"
description = "Zed's `http_client_tls` crate (gpui-pre snapshot of zed@d748a75)"
repository = "https://github.com/zed-industries/zed"

[package.metadata.gpui-pre]
zed-crate = "http_client_tls"
zed-version = "0.1.0"
zed-rev = "d748a758d82478ae8054827f466fff0fffb47056"

[lib]
path = "src/http_client_tls.rs"
doctest = false
test = false
name = "http_client_tls"

[features]
test-support = []

[dependencies]
log = { workspace = true, features = ["serde"] }
rustls = { workspace = true }
rustls-platform-verifier = { workspace = true }
webpki-roots = { workspace = true }

[lints]
workspace = true
