[package]
name = "gpui-pre-ztracing"
version = "0.3.124"
edition = { workspace = true }
publish = true
license = "Apache-2.0"
description = "Zed's `ztracing` crate (gpui-pre snapshot of zed@d8bc772)"
repository = "https://github.com/zed-industries/zed"

[package.metadata.gpui-pre]
zed-crate = "ztracing"
zed-version = "0.1.0"
zed-rev = "d8bc7723f2bdf220cc0cc048160f425afc74de49"

[lib]
doctest = false
name = "ztracing"

[features]
tracing-tracy = ["dep:tracing-tracy", "dep:tracing-subscriber", "dep:zlog"]
tracy = ["tracing-tracy", "tracy-client"]
web = [
    "dep:async-channel",
    "dep:js-sys",
    "dep:tracing-subscriber",
    "dep:wasm-bindgen",
    "dep:web-sys",
    "dep:zlog",
]

[dependencies]
zlog = { workspace = true, optional = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, optional = true }
ztracing_macro = { workspace = true }

[target.'cfg(not(target_family = "wasm"))'.dependencies]
tracing-tracy = { version = "0.11", optional = true, features = ["ondemand"] }
tracy-client = { version = "0.18", optional = true, features = ["ondemand"] }

[target.'cfg(target_family = "wasm")'.dependencies]
async-channel = { workspace = true, features = ["std"], optional = true }
js-sys = { workspace = true, optional = true }
wasm-bindgen = { workspace = true, optional = true }
web-sys = { workspace = true, features = ["console", "Performance"], optional = true }

[lints]
workspace = true
