[package]
name = "gpui-pre-scheduler"
version = "0.3.124"
edition = { workspace = true }
publish = true
license = "Apache-2.0"
description = "Zed's `scheduler` crate (gpui-pre snapshot of zed@d8bc772)"
repository = "https://github.com/zed-industries/zed"

[package.metadata.gpui-pre]
zed-crate = "scheduler"
zed-version = "0.1.0"
zed-rev = "d8bc7723f2bdf220cc0cc048160f425afc74de49"

[lib]
path = "src/scheduler.rs"
doctest = false
name = "scheduler"

[features]
test-support = []
wasm-threads = ["dep:wasm_thread", "flume/spin"]

[dependencies]
async-task = { workspace = true }
backtrace = { workspace = true }
chrono = { workspace = true, features = ["now", "wasmbind"] }
flume = { workspace = true }
futures = { workspace = true }
parking_lot = { workspace = true }
rand = { workspace = true }
web-time = { workspace = true }

[target.'cfg(target_family = "wasm")'.dependencies]
wasm_thread = { workspace = true, optional = true }

[lints]
workspace = true
