[package]
name = "gpui-pre-wgpu"
version = "0.3.125"
edition = { workspace = true }
publish = true
license = "Apache-2.0"
description = "Zed's `gpui_wgpu` crate (gpui-pre snapshot of zed@d748a75)"
repository = "https://github.com/zed-industries/zed"

[package.metadata.gpui-pre]
zed-crate = "gpui_wgpu"
zed-version = "0.1.0"
zed-rev = "d748a758d82478ae8054827f466fff0fffb47056"

[lib]
path = "src/gpui_wgpu.rs"
doctest = false
name = "gpui_wgpu"

[features]
default = []
bench-support = ["gpui/bench-support", "dep:image"]
font-kit = ["dep:font-kit"]
test-support = ["gpui/test-support", "dep:image"]

[dependencies]
gpui = { workspace = true }
anyhow = { workspace = true }
bytemuck = { workspace = true }
collections = { workspace = true }
cosmic-text = "0.19.0"
etagere = { workspace = true }
itertools = { workspace = true }
image = { workspace = true, optional = true }
log = { workspace = true }
parking_lot = { workspace = true }
profiling = { workspace = true }
raw-window-handle = { workspace = true }
smallvec = { workspace = true }
swash = { workspace = true }
unicode-bidi = { workspace = true }
unicode-segmentation = { workspace = true }
gpui_util = { workspace = true }
font-kit = { workspace = true, optional = true }

[target.'cfg(any(target_os = "linux", target_os = "freebsd"))'.dependencies]
wgpu = { workspace = true, features = ["std", "parking_lot", "metal", "gles", "vulkan", "wgsl", "webgpu"] }

[target.'cfg(not(any(target_os = "linux", target_os = "freebsd")))'.dependencies]
wgpu = { workspace = true, default-features = true }

[target.'cfg(target_family = "wasm")'.dependencies]
web-sys = { workspace = true, features = ["HtmlCanvasElement"] }
wgpu = { workspace = true, features = ["webgl"] }

[lints]
workspace = true

[[bench]]
name = "layout_line"
harness = false
