[package]
name = "gpui-pre-http-client"
version = "0.3.124"
edition = { workspace = true }
publish = true
license = "Apache-2.0"
description = "A HTTP client library for Zed and GPUI (gpui-pre snapshot of zed@d8bc772)"
repository = "https://github.com/zed-industries/zed"

[package.metadata.gpui-pre]
zed-crate = "http_client"
zed-version = "0.1.0"
zed-rev = "d8bc7723f2bdf220cc0cc048160f425afc74de49"

[lib]
path = "src/http_client.rs"
doctest = false
name = "http_client"

[features]
test-support = ["dep:log"]

[dependencies]
anyhow = { workspace = true }
bytes = { workspace = true }
futures = { workspace = true }
http-body = { workspace = true }
http = { workspace = true }
log = { workspace = true, optional = true }
parking_lot = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_urlencoded = { workspace = true }
url = { workspace = true }

[target.'cfg(not(target_family = "wasm"))'.dependencies]
log = { workspace = true }

[lints]
workspace = true
