[package]
name = "gpui-pre-shared-string"
version = "0.3.99"
publish = true
edition = { workspace = true }
license = "Apache-2.0"
description = "Zed's `gpui_shared_string` crate (gpui-pre snapshot of zed@14469e0)"
repository = "https://github.com/zed-industries/zed"

[package.metadata.gpui-pre]
zed-crate = "gpui_shared_string"
zed-version = "0.1.0"
zed-rev = "14469e0061621291fb283f1956f40c266a634782"

[lib]
path = "gpui_shared_string.rs"
test = false
doctest = false
name = "gpui_shared_string"

[features]

[dependencies]
schemars = { workspace = true }
serde = { workspace = true }
smol_str = "0.3.6"

[lints]
workspace = true
