[package]
name = "gpui-pre-util"
version = "0.3.99"
publish = true
edition = { workspace = true }
license = "Apache-2.0"
description = "Zed's `gpui_util` crate (gpui-pre snapshot of zed@29281f0)"
repository = "https://github.com/zed-industries/zed"

[package.metadata.gpui-pre]
zed-crate = "gpui_util"
zed-version = "0.1.0"
zed-rev = "29281f02c8f51a3bfa0910a9ea11724970227f49"

[lib]
name = "gpui_util"

[features]

[dependencies]
log = { workspace = true }
anyhow = { workspace = true }

[target.'cfg(target_os = "windows")'.dependencies]
which = { workspace = true }

[lints]
workspace = true
