[package]
name = "gpui-pre-zlog"
version = "0.3.123"
edition = { workspace = true }
publish = true
license = "Apache-2.0"
description = "Zed's `zlog` crate (gpui-pre snapshot of zed@b032bf6)"
repository = "https://github.com/zed-industries/zed"

[package.metadata.gpui-pre]
zed-crate = "zlog"
zed-version = "0.1.0"
zed-rev = "b032bf62e97361374175ae5711a5aef221dd8206"

[lib]
path = "src/zlog.rs"
doctest = false
name = "zlog"

[features]
default = []

[dependencies]
collections = { workspace = true }
chrono = { workspace = true }
log = { workspace = true }
anyhow = { workspace = true }

[lints]
workspace = true
