[package]
name = "gpui-pre-zlog"
version = "0.3.120"
edition = { workspace = true }
publish = true
license = "Apache-2.0"
description = "Zed's `zlog` crate (gpui-pre snapshot of zed@7485783)"
repository = "https://github.com/zed-industries/zed"

[package.metadata.gpui-pre]
zed-crate = "zlog"
zed-version = "0.1.0"
zed-rev = "7485783f8027adba8795bcc2341bff7158791b3d"

[lib]
path = "src/zlog.rs"
doctest = false
name = "zlog"

[features]
default = []

[dependencies]
collections = { workspace = true }
chrono = { workspace = true }
log = { workspace = true }
anyhow = { workspace = true }

[lints]
workspace = true
