[package]
name = "gpui-pre-refineable"
version = "0.3.118"
edition = { workspace = true }
publish = true
license = "Apache-2.0"
description = "A macro for creating 'refinement' types that can be used to partially initialize or mutate a complex struct (gpui-pre snapshot of zed@41d65c8)"
repository = "https://github.com/zed-industries/zed"

[package.metadata.gpui-pre]
zed-crate = "refineable"
zed-version = "0.1.0"
zed-rev = "41d65c89293a833a656478263fa1dd308613a372"

[lib]
path = "src/refineable.rs"
doctest = false
test = false
name = "refineable"

[features]

[dependencies]
derive_refineable = { workspace = true }

[lints]
workspace = true
