[package]
name = "gpui-pre-ztracing-macro"
version = "0.3.118"
edition = { workspace = true }
publish = true
license = "Apache-2.0"
description = "Zed's `ztracing_macro` crate (gpui-pre snapshot of zed@41d65c8)"
repository = "https://github.com/zed-industries/zed"

[package.metadata.gpui-pre]
zed-crate = "ztracing_macro"
zed-version = "0.1.0"
zed-rev = "41d65c89293a833a656478263fa1dd308613a372"

[lib]
proc-macro = true
test = false
doctest = false
name = "ztracing_macro"

[features]
