[package]
name = "gpui-pre-ztracing-macro"
version = "0.3.123"
edition = { workspace = true }
publish = true
license = "Apache-2.0"
description = "Zed's `ztracing_macro` crate (gpui-pre snapshot of zed@b032bf6)"
repository = "https://github.com/zed-industries/zed"

[package.metadata.gpui-pre]
zed-crate = "ztracing_macro"
zed-version = "0.1.0"
zed-rev = "b032bf62e97361374175ae5711a5aef221dd8206"

[lib]
proc-macro = true
test = false
doctest = false
name = "ztracing_macro"

[features]
