[package]
name = "gpui-pre-ztracing-macro"
version = "0.3.119"
edition = { workspace = true }
publish = true
license = "Apache-2.0"
description = "Zed's `ztracing_macro` crate (gpui-pre snapshot of zed@b73d4c2)"
repository = "https://github.com/zed-industries/zed"

[package.metadata.gpui-pre]
zed-crate = "ztracing_macro"
zed-version = "0.1.0"
zed-rev = "b73d4c2b257b6a8cf2440fe1f5314aff6e73f3e3"

[lib]
proc-macro = true
test = false
doctest = false
name = "ztracing_macro"

[features]
