[package]
name = "gpui-pre-util-macros"
version = "0.3.99"
edition = { workspace = true }
publish = true
license = "Apache-2.0"
description = "Utility macros for Zed (gpui-pre snapshot of zed@043fe99)"
repository = "https://github.com/zed-industries/zed"

[package.metadata.gpui-pre]
zed-crate = "util_macros"
zed-version = "0.1.0"
zed-rev = "043fe9923e8a3935e3d084eb159082b26200a592"

[lib]
path = "src/util_macros.rs"
proc-macro = true
doctest = false
name = "util_macros"

[features]
perf-enabled = []

[dependencies]
quote = { workspace = true }
syn = { workspace = true }
perf = { workspace = true }

[lints]
workspace = true
