[package]
name = "gpui-pre-derive-refineable"
version = "0.3.124"
edition = { workspace = true }
publish = true
license = "Apache-2.0"
description = "A derive macro for creating refinement types in Rust (gpui-pre snapshot of zed@d8bc772)"
repository = "https://github.com/zed-industries/zed"

[package.metadata.gpui-pre]
zed-crate = "derive_refineable"
zed-version = "0.1.0"
zed-rev = "d8bc7723f2bdf220cc0cc048160f425afc74de49"

[lib]
path = "src/derive_refineable.rs"
proc-macro = true
doctest = false
test = false
name = "derive_refineable"

[features]

[dependencies]
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true, default-features = true }

[lints]
workspace = true
